<!-- prettier-ignore -->
<template>
  <div>
<p>
    <meta charset="utf-8">
</p>
<div class="row mb-4" style='font-family: tfutura, -apple-system, system-ui, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"; box-sizing: content-box; color: rgb(33, 37, 41); display: flex; flex-wrap: wrap; margin-right: -15px; margin-left: -15px; margin-bottom: 1.5rem !important; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(254, 254, 254); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>
    <div class="col" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41); position: relative; width: 1008px; min-height: 1px; padding-right: 15px; padding-left: 15px; flex-basis: 0px; flex-grow: 1; max-width: 100%;'>
        <h4 style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; margin-top: 0px; margin-bottom: 0.5rem; line-height: 1.1; color: rgb(33, 37, 41); font-size: 1.5rem; font-weight: 300;'><strong style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; font-weight: bolder; color: rgb(33, 37, 41);'>Политика в отношении обработки персональных данных</strong></h4>
    </div>
</div>
<div class="row mb-4" style='font-family: tfutura, -apple-system, system-ui, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"; box-sizing: content-box; color: rgb(33, 37, 41); display: flex; flex-wrap: wrap; margin-right: -15px; margin-left: -15px; margin-bottom: 1.5rem !important; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(254, 254, 254); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>
    <div class="col" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41); position: relative; width: 1008px; min-height: 1px; padding-right: 15px; padding-left: 15px; flex-basis: 0px; flex-grow: 1; max-width: 100%;'>
        <h5 style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; margin-top: 0px; font-weight: 500; margin-bottom: 0.5rem; line-height: 1.1; color: rgb(33, 37, 41); font-size: 1.25rem; display: inline;'>1. Общие положения</h5>
        <div class="descr" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41);'>Настоящая политика обработки персональных данных составлена в соответствии с требованиями Федерального закона от 27.07.2006. №152-ФЗ &laquo;О персональных данных&raquo; и определяет порядок обработки персональных данных и меры по обеспечению безопасности персональных данных, предпринимаемые&nbsp;<span class="link mark" data-scroll-to="#privacyName" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41); display: inline; padding: 0.05em; background-color: rgb(252, 248, 227); cursor: pointer; border-bottom: 1.5px dotted rgb(250, 134, 105);'>Колосов Роман Владимирович</span> (далее &ndash; Оператор).</div>
        <div class="ol" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41); margin-bottom: 1rem; padding-left: 40px;'>
            <div class="li" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41);'>1.1. Оператор ставит своей важнейшей целью и условием осуществления своей деятельности соблюдение прав и свобод человека и гражданина при обработке его персональных данных, в том числе защиты прав на неприкосновенность частной жизни, личную и семейную тайну.</div>
            <div class="li" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41);'>1.2. Настоящая политика Оператора в отношении обработки персональных данных (далее &ndash; Политика) применяется ко всей информации, которую Оператор может получить о посетителях веб-сайта&nbsp;<span class="link mark" data-scroll-to="#prefixURL" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41); display: inline; padding: 0.05em; background-color: rgb(252, 248, 227); cursor: pointer; border-bottom: 1.5px dotted rgb(250, 134, 105);'>http://rvkolosov.ru</span>.</div>
        </div>
    </div>
</div>
<div class="row" style='font-family: tfutura, -apple-system, system-ui, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"; box-sizing: content-box; color: rgb(33, 37, 41); display: flex; flex-wrap: wrap; margin-right: -15px; margin-left: -15px; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(254, 254, 254); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>&nbsp;</div>
<div class="row mb-4" style='font-family: tfutura, -apple-system, system-ui, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"; box-sizing: content-box; color: rgb(33, 37, 41); display: flex; flex-wrap: wrap; margin-right: -15px; margin-left: -15px; margin-bottom: 1.5rem !important; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(254, 254, 254); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>
    <div class="col" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41); position: relative; width: 1008px; min-height: 1px; padding-right: 15px; padding-left: 15px; flex-basis: 0px; flex-grow: 1; max-width: 100%;'>
        <h5 style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; margin-top: 0px; font-weight: 500; margin-bottom: 0.5rem; line-height: 1.1; color: rgb(33, 37, 41); font-size: 1.25rem; display: inline;'>2. Основные понятия, используемые в Политике</h5>
        <div class="ol" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41); margin-bottom: 1rem; padding-left: 40px;'>
            <div class="li" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41);'>2.1. Автоматизированная обработка персональных данных &ndash; обработка персональных данных с помощью средств вычислительной техники;</div>
            <div class="li" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41);'>2.2. Блокирование персональных данных &ndash; временное прекращение обработки персональных данных (за исключением случаев, если обработка необходима для уточнения персональных данных);</div>
            <div class="li" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41);'>2.3. Веб-сайт &ndash; совокупность графических и информационных материалов, а также программ для ЭВМ и баз данных, обеспечивающих их доступность в сети интернет по сетевому адресу&nbsp;<span class="link mark" data-scroll-to="#prefixURL" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41); display: inline; padding: 0.05em; background-color: rgb(252, 248, 227); cursor: pointer; border-bottom: 1.5px dotted rgb(250, 134, 105);'>http://rvkolosov.ru</span>;</div>
            <div class="li" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41);'>2.4. Информационная система персональных данных &mdash; совокупность содержащихся в базах данных персональных данных, и обеспечивающих их обработку информационных технологий и технических средств;</div>
            <div class="li" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41);'>2.5. Обезличивание персональных данных &mdash; действия, в результате которых невозможно определить без использования дополнительной информации принадлежность персональных данных конкретному Пользователю или иному субъекту персональных данных;</div>
            <div class="li" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41);'>2.6. Обработка персональных данных &ndash; любое действие (операция) или совокупность действий (операций), совершаемых с использованием средств автоматизации или без использования таких средств с персональными данными, включая сбор, запись, систематизацию, накопление, хранение, уточнение (обновление, изменение), извлечение, использование, передачу (распространение, предоставление, доступ), обезличивание, блокирование, удаление, уничтожение персональных данных;</div>
            <div class="li" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41);'>2.7. Оператор &ndash; государственный орган, муниципальный орган, юридическое или физическое лицо, самостоятельно или совместно с другими лицами организующие и (или) осуществляющие обработку персональных данных, а также определяющие цели обработки персональных данных, состав персональных данных, подлежащих обработке, действия (операции), совершаемые с персональными данными;</div>
            <div class="li" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41);'>2.8. Персональные данные &ndash; любая информация, относящаяся прямо или косвенно к определенному или определяемому Пользователю веб-сайта&nbsp;<span class="link mark" data-scroll-to="#prefixURL" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41); display: inline; padding: 0.05em; background-color: rgb(252, 248, 227); cursor: pointer; border-bottom: 1.5px dotted rgb(250, 134, 105);'>http://rvkolosov.ru</span>;</div>
            <div class="li" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41);'>2.9. Пользователь &ndash; любой посетитель веб-сайта&nbsp;<span class="link mark" data-scroll-to="#prefixURL" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41); display: inline; padding: 0.05em; background-color: rgb(252, 248, 227); cursor: pointer; border-bottom: 1.5px dotted rgb(250, 134, 105);'>http://rvkolosov.ru</span>;</div>
            <div class="li" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41);'>2.10. Предоставление персональных данных &ndash; действия, направленные на раскрытие персональных данных определенному лицу или определенному кругу лиц;</div>
            <div class="li" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41);'>2.11. Распространение персональных данных &ndash; любые действия, направленные на раскрытие персональных данных неопределенному кругу лиц (передача персональных данных) или на ознакомление с персональными данными неограниченного круга лиц, в том числе обнародование персональных данных в средствах массовой информации, размещение в информационно-телекоммуникационных сетях или предоставление доступа к персональным данным каким-либо иным способом;</div>
            <div class="li" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41);'>2.12. Трансграничная передача персональных данных &ndash; передача персональных данных на территорию иностранного государства органу власти иностранного государства, иностранному физическому или иностранному юридическому лицу;</div>
            <div class="li" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41);'>2.13. Уничтожение персональных данных &ndash; любые действия, в результате которых персональные данные уничтожаются безвозвратно с невозможностью дальнейшего восстановления содержания персональных данных в информационной системе персональных данных и (или) уничтожаются материальные носители персональных данных.</div>
        </div>
    </div>
</div>
<div class="row" style='font-family: tfutura, -apple-system, system-ui, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"; box-sizing: content-box; color: rgb(33, 37, 41); display: flex; flex-wrap: wrap; margin-right: -15px; margin-left: -15px; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(254, 254, 254); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>&nbsp;</div>
<div class="row mb-4" style='font-family: tfutura, -apple-system, system-ui, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"; box-sizing: content-box; color: rgb(33, 37, 41); display: flex; flex-wrap: wrap; margin-right: -15px; margin-left: -15px; margin-bottom: 1.5rem !important; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(254, 254, 254); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>
    <div class="col" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41); position: relative; width: 1008px; min-height: 1px; padding-right: 15px; padding-left: 15px; flex-basis: 0px; flex-grow: 1; max-width: 100%;'>
        <h5 style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; margin-top: 0px; font-weight: 500; margin-bottom: 0.5rem; line-height: 1.1; color: rgb(33, 37, 41); font-size: 1.25rem; display: inline;'>3. Оператор может обрабатывать следующие персональные данные Пользователя</h5>
        <div class="ol" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41); margin-bottom: 1rem; padding-left: 40px;'>
            <div style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41);'>3.1.&nbsp;<mark style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; display: inline; padding: 0.05em; background-color: rgb(252, 248, 227); color: rgb(33, 37, 41);'>Фамилия, имя, отчество;</mark></div>
            <div style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41);'>3.2.&nbsp;<mark style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; display: inline; padding: 0.05em; background-color: rgb(252, 248, 227); color: rgb(33, 37, 41);'>Электронный адрес;</mark></div>
            <div style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41);'>3.3.&nbsp;<mark style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; display: inline; padding: 0.05em; background-color: rgb(252, 248, 227); color: rgb(33, 37, 41);'>Номера телефонов;</mark></div>
            <div style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41);'>3.4.&nbsp;<mark style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; display: inline; padding: 0.05em; background-color: rgb(252, 248, 227); color: rgb(33, 37, 41);'>Год, месяц, дата и место рождения;</mark></div>
            <div style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41);'>3.5.&nbsp;<mark style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; display: inline; padding: 0.05em; background-color: rgb(252, 248, 227); color: rgb(33, 37, 41);'>Фотографии;</mark></div>
            <div style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41);'>3.6. Также на сайте происходит сбор и обработка обезличенных данных о посетителях (в т.ч. файлов &laquo;cookie&raquo;) с помощью сервисов интернет-статистики (Яндекс Метрика и Гугл Аналитика и других).</div>
            <div style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41);'>3.7. Вышеперечисленные данные далее по тексту Политики объединены общим понятием Персональные данные.</div>
        </div>
    </div>
</div>
<div class="row" style='font-family: tfutura, -apple-system, system-ui, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"; box-sizing: content-box; color: rgb(33, 37, 41); display: flex; flex-wrap: wrap; margin-right: -15px; margin-left: -15px; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(254, 254, 254); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>&nbsp;</div>
<div class="row mb-4" style='font-family: tfutura, -apple-system, system-ui, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"; box-sizing: content-box; color: rgb(33, 37, 41); display: flex; flex-wrap: wrap; margin-right: -15px; margin-left: -15px; margin-bottom: 1.5rem !important; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(254, 254, 254); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>
    <div class="col" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41); position: relative; width: 1008px; min-height: 1px; padding-right: 15px; padding-left: 15px; flex-basis: 0px; flex-grow: 1; max-width: 100%;'>
        <h5 style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; margin-top: 0px; font-weight: 500; margin-bottom: 0.5rem; line-height: 1.1; color: rgb(33, 37, 41); font-size: 1.25rem; display: inline;'>4. Цели обработки персональных данных</h5>
        <div class="ol" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41); margin-bottom: 1rem; padding-left: 40px;'>
            <div class="li" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41);'>4.1. Цель обработки персональных данных Пользователя &mdash;&nbsp;<mark style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; display: inline; padding: 0.05em; background-color: rgb(252, 248, 227); color: rgb(33, 37, 41);'>информирование Пользователя посредством отправки электронных писем; заключение, исполнение и прекращение гражданско-правовых договоров; предоставление доступа Пользователю к сервисам, информации и/или материалам, содержащимся на веб-сайте</mark>.</div>
            <div class="li" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41);'>4.2. Также Оператор имеет право направлять Пользователю уведомления о новых продуктах и услугах, специальных предложениях и различных событиях. Пользователь всегда может отказаться от получения информационных сообщений, направив Оператору письмо на адрес электронной почты&nbsp;<span class="link mark" data-scroll-to="#privacyEmail" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41); display: inline; padding: 0.05em; background-color: rgb(252, 248, 227); cursor: pointer; border-bottom: 1.5px dotted rgb(250, 134, 105);'>roman.kolosov12@yandex.ru</span> с пометкой &laquo;Отказ от уведомлений о новых продуктах и услугах и специальных предложениях&raquo;.</div>
            <div class="li" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41);'>4.3. Обезличенные данные Пользователей, собираемые с помощью сервисов интернет-статистики, служат для сбора информации о действиях Пользователей на сайте, улучшения качества сайта и его содержания.</div>
        </div>
    </div>
</div>
<div class="row" style='font-family: tfutura, -apple-system, system-ui, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"; box-sizing: content-box; color: rgb(33, 37, 41); display: flex; flex-wrap: wrap; margin-right: -15px; margin-left: -15px; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(254, 254, 254); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>&nbsp;</div>
<div class="row mb-4" style='font-family: tfutura, -apple-system, system-ui, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"; box-sizing: content-box; color: rgb(33, 37, 41); display: flex; flex-wrap: wrap; margin-right: -15px; margin-left: -15px; margin-bottom: 1.5rem !important; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(254, 254, 254); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>
    <div class="col" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41); position: relative; width: 1008px; min-height: 1px; padding-right: 15px; padding-left: 15px; flex-basis: 0px; flex-grow: 1; max-width: 100%;'>
        <h5 style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; margin-top: 0px; font-weight: 500; margin-bottom: 0.5rem; line-height: 1.1; color: rgb(33, 37, 41); font-size: 1.25rem; display: inline;'>5. Правовые основания обработки персональных данных</h5>
        <div class="ol" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41); margin-bottom: 1rem; padding-left: 40px;'>
            <div class="li" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41);'>5.1. Оператор обрабатывает персональные данные Пользователя только в случае их заполнения и/или отправки Пользователем самостоятельно через специальные формы, расположенные на сайте&nbsp;<span class="link mark" data-scroll-to="#prefixURL" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41); display: inline; padding: 0.05em; background-color: rgb(252, 248, 227); cursor: pointer; border-bottom: 1.5px dotted rgb(250, 134, 105);'>http://rvkolosov.ru</span>. Заполняя соответствующие формы и/или отправляя свои персональные данные Оператору, Пользователь выражает свое согласие с данной Политикой.</div>
            <div class="li" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41);'>5.2. Оператор обрабатывает обезличенные данные о Пользователе в случае, если это разрешено в настройках браузера Пользователя (включено сохранение файлов &laquo;cookie&raquo; и использование технологии JavaScript).</div>
        </div>
    </div>
</div>
<div class="row" style='font-family: tfutura, -apple-system, system-ui, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"; box-sizing: content-box; color: rgb(33, 37, 41); display: flex; flex-wrap: wrap; margin-right: -15px; margin-left: -15px; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(254, 254, 254); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>&nbsp;</div>
<div class="row mb-4" style='font-family: tfutura, -apple-system, system-ui, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"; box-sizing: content-box; color: rgb(33, 37, 41); display: flex; flex-wrap: wrap; margin-right: -15px; margin-left: -15px; margin-bottom: 1.5rem !important; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(254, 254, 254); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>
    <div class="col" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41); position: relative; width: 1008px; min-height: 1px; padding-right: 15px; padding-left: 15px; flex-basis: 0px; flex-grow: 1; max-width: 100%;'>
        <h5 style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; margin-top: 0px; font-weight: 500; margin-bottom: 0.5rem; line-height: 1.1; color: rgb(33, 37, 41); font-size: 1.25rem; display: inline;'>6. Порядок сбора, хранения, передачи и других видов обработки персональных данных</h5>
        <div class="descr" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41);'>Безопасность персональных данных, которые обрабатываются Оператором, обеспечивается путем реализации правовых, организационных и технических мер, необходимых для выполнения в полном объеме требований действующего законодательства в области защиты персональных данных.</div>
        <div class="ol" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41); margin-bottom: 1rem; padding-left: 40px;'>
            <div class="li" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41);'>6.1. Оператор обеспечивает сохранность персональных данных и принимает все возможные меры, исключающие доступ к персональным данным неуполномоченных лиц.</div>
            <div class="li" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41);'>6.2. Персональные данные Пользователя никогда, ни при каких условиях не будут переданы третьим лицам, за исключением случаев, связанных с исполнением действующего законодательства.</div>
            <div class="li" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41);'>6.3. В случае выявления неточностей в персональных данных, Пользователь может актуализировать их самостоятельно, путем направления Оператору уведомление на адрес электронной почты Оператора&nbsp;<span class="link mark" data-scroll-to="#privacyEmail" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41); display: inline; padding: 0.05em; background-color: rgb(252, 248, 227); cursor: pointer; border-bottom: 1.5px dotted rgb(250, 134, 105);'>roman.kolosov12@yandex.ru</span> с пометкой &laquo;Актуализация персональных данных&raquo;.</div>
            <div class="li" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41);'>6.4. Срок обработки персональных данных является неограниченным. Пользователь может в любой момент отозвать свое согласие на обработку персональных данных, направив Оператору уведомление посредством электронной почты на электронный адрес Оператора&nbsp;<span class="link mark" data-scroll-to="#privacyEmail" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41); display: inline; padding: 0.05em; background-color: rgb(252, 248, 227); cursor: pointer; border-bottom: 1.5px dotted rgb(250, 134, 105);'>roman.kolosov12@yandex.ru</span> с пометкой &laquo;Отзыв согласия на обработку персональных данных&raquo;.</div>
        </div>
    </div>
</div>
<div class="row" style='font-family: tfutura, -apple-system, system-ui, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"; box-sizing: content-box; color: rgb(33, 37, 41); display: flex; flex-wrap: wrap; margin-right: -15px; margin-left: -15px; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(254, 254, 254); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>&nbsp;</div>
<div class="row mb-4" style='font-family: tfutura, -apple-system, system-ui, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"; box-sizing: content-box; color: rgb(33, 37, 41); display: flex; flex-wrap: wrap; margin-right: -15px; margin-left: -15px; margin-bottom: 1.5rem !important; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(254, 254, 254); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>
    <div class="col" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41); position: relative; width: 1008px; min-height: 1px; padding-right: 15px; padding-left: 15px; flex-basis: 0px; flex-grow: 1; max-width: 100%;'>
        <h5 style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; margin-top: 0px; font-weight: 500; margin-bottom: 0.5rem; line-height: 1.1; color: rgb(33, 37, 41); font-size: 1.25rem; display: inline;'>7. Трансграничная передача персональных данных</h5>
        <div class="ol" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41); margin-bottom: 1rem; padding-left: 40px;'>
            <div class="li" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41);'>7.1. Оператор до начала осуществления трансграничной передачи персональных данных обязан убедиться в том, что иностранным государством, на территорию которого предполагается осуществлять передачу персональных данных, обеспечивается надежная защита прав субъектов персональных данных.</div>
            <div class="li" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41);'>7.2. Трансграничная передача персональных данных на территории иностранных государств, не отвечающих вышеуказанным требованиям, может осуществляться только в случае наличия согласия в письменной форме субъекта персональных данных на трансграничную передачу его персональных данных и/или исполнения договора, стороной которого является субъект персональных данных.</div>
        </div>
    </div>
</div>
<div class="row" style='font-family: tfutura, -apple-system, system-ui, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"; box-sizing: content-box; color: rgb(33, 37, 41); display: flex; flex-wrap: wrap; margin-right: -15px; margin-left: -15px; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(254, 254, 254); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>&nbsp;</div>
<div class="row mb-4" style='font-family: tfutura, -apple-system, system-ui, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"; box-sizing: content-box; color: rgb(33, 37, 41); display: flex; flex-wrap: wrap; margin-right: -15px; margin-left: -15px; margin-bottom: 1.5rem !important; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(254, 254, 254); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>
    <div class="col" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41); position: relative; width: 1008px; min-height: 1px; padding-right: 15px; padding-left: 15px; flex-basis: 0px; flex-grow: 1; max-width: 100%;'>
        <h5 style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; margin-top: 0px; font-weight: 500; margin-bottom: 0.5rem; line-height: 1.1; color: rgb(33, 37, 41); font-size: 1.25rem; display: inline;'>8. Заключительные положения</h5>
        <div class="ol" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41); margin-bottom: 1rem; padding-left: 40px;'>
            <div class="li" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41);'>8.1. Пользователь может получить любые разъяснения по интересующим вопросам, касающимся обработки его персональных данных, обратившись к Оператору с помощью электронной почты&nbsp;<span class="link mark" data-scroll-to="#privacyEmail" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41); display: inline; padding: 0.05em; background-color: rgb(252, 248, 227); cursor: pointer; border-bottom: 1.5px dotted rgb(250, 134, 105);'>roman.kolosov12@yandex.ru</span>.</div>
            <div class="li" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41);'>8.2. В данном документе будут отражены любые изменения политики обработки персональных данных Оператором. Политика действует бессрочно до замены ее новой версией.</div>
            <div class="li" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41);'>8.3. Актуальная версия Политики в свободном доступе расположена в сети Интернет по адресу&nbsp;<span class="link mark" data-scroll-to="#prefixURLLink" style='font-family: tfutura, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important; box-sizing: content-box; color: rgb(33, 37, 41); display: inline; padding: 0.05em; background-color: rgb(252, 248, 227); cursor: pointer; border-bottom: 1.5px dotted rgb(250, 134, 105);'>http://rvkolosov.ru/privacy</span>.</div>
        </div>
    </div>
</div>
  </div>
</template>

<script>
export default {}
</script>
